logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
spring:
  application:
    name: monopoly
server:
  port: 8080

customize:
  initMoney: 15200
  users:
    - name: 寂弦
      nick: 弦
      color: cornflowerblue
      token: zzx

    - name: 钻头
      nick: 钻
      color: darkslategray
      token: sgj

    - name: 屈屈
      nick: 屈
      color: burlywood
      token: qzx
    - name: 玉婷
      nick: 婷
      color: indianred
      token: syt
  maps:
    - name: 起点
      type: start

    - name: 中山北路
      type: estate
      color: pink
      price: 600
      detail: 20,100,300,900,1600,2500,500

    - name: 欢乐卡
      type: happy

    - name: 中山南一路
      type: estate
      color: pink
      price: 600
      detail: 40,200,600,1800,3200,4500,500

    - name: 所得税
      type: tax
      price: 2000

    - name: 人民广场车站
      type: station
      price: 2000
      detail: 250,500,1000,2000

    - name: 交通路
      type: estate
      color: blue
      price: 1000
      detail: 60,300,900,2700,4000,5500,500

    - name: 机会
      type: chance

    - name: 四川北路
      type: estate
      color: blue
      price: 1000
      detail: 60,300,900,2700,4000,5500,500

    - name: 金宁东路
      type: estate
      color: blue
      price: 1200
      detail: 80,400,1000,3000,4500,6000,500

    - name: 坐牢/路过
      type: other

    - name: 中华路
      type: estate
      color: darkblue
      price: 1400
      detail: 100,500,1500,4000,6250,7500,1000

    - name: 电力公司
      type: livelihood
      price: 1500

    - name: 四平路
      type: estate
      color: darkblue
      price: 1400
      detail: 100,500,1500,4000,6250,7500,1000

    - name: 浦东南路
      type: estate
      color: darkblue
      price: 1600
      detail: 120,600,1800,5000,7000,9000,1000

    - name: 徐家汇车站
      type: station
      price: 2000
      detail: 250,500,1000,2000

    - name: 恒丰路
      type: estate
      color: orange
      price: 1800
      detail: 140,700,2000,5500,7500,9500,1000

    - name: 命运
      type: destiny

    - name: 河南北路
      type: estate
      color: orange
      price: 1800
      detail: 140,700,2000,5500,7500,9500,1000

    - name: 西藏中路
      type: estate
      color: orange
      price: 2000
      detail: 160,800,2200,6000,8000,10000,1000

    - name: 免费停车场
      type: other

    - name: 石门二路
      type: estate
      color: red
      price: 2200
      detail: 180,900,2500,7000,8750,10500,1500

    - name: 机会
      type: chance

    - name: 陕西南路
      type: estate
      color: red
      price: 2200
      detail: 180,900,2500,7000,8750,10500,1500

    - name: 天目路
      type: estate
      color: red
      price: 2400
      detail: 200,1000,3000,7500,9250,11000,1500

    - name: 汉中车站
      type: station
      price: 2000
      detail: 250,500,1000,2000

    - name: 长寿路
      type: estate
      color: chocolate
      price: 2600
      detail: 220,1100,3300,8000,9750,11500,1500

    - name: 延安西路
      type: estate
      color: chocolate
      price: 2600
      detail: 220,1100,3300,8000,9750,11500,1500

    - name: 自来水厂
      type: livelihood
      price: 1500

    - name: 人民路
      type: estate
      color: chocolate
      price: 2600
      detail: 220,1100,3300,8000,9750,11500,1500

    - name: 进牢
      type: prison

    - name: 淮海中路
      type: estate
      color: green
      price: 3000
      detail: 260,1300,3900,9000,11000,12750,2000

    - name: 复兴中路
      type: estate
      color: green
      price: 3000
      detail: 260,1300,3900,9000,11000,12750,2000

    - name: 命运
      type: destiny

    - name: 建国东路
      type: estate
      color: green
      price: 3200
      detail: 280,1500,4500,10000,12000,14000,2000

    - name: 上海车站
      type: station
      price: 2000
      detail: 250,500,1000,2000

    - name: 机会
      type: chance

    - name: 南京西路
      type: estate
      color: darkslategray
      price: 3500
      detail: 350,1750,5000,11000,13000,15000,2000

    - name: 所得税
      type: tax
      price: 1000

    - name: 北京东路
      type: estate
      color: darkslategray
      price: 4000
      detail: 500,2000,6000,14000,17000,20000,2000
  destiny:
    - name: 与木乃伊合照冲洗相片，费用300
      type: cost
      price: 300
    - name: 当棉被一条，得500
      type: gain
      price: 500
    - name: 出狱许可证
      type: impunity
      price: 0
    - name: 选美会获亚军，得1000
      type: gain
      price: 1000
    - name: 这是你的生日，向每人收取礼金1000
      type: gainFromOther
      price: 1000
    - name: 得美国华盛顿大学奖学金2000
      type: gain
      price: 2000
    - name: 拘票，立刻坐牢
      type: jailed
      price: 0
    - name: 小偷光顾，损失500
      type: cost
      price: 500
    - name: 敬军爱国，捐款1000
      type: cost
      price: 1000
    - name: 付产科医院1000
      type: cost
      price: 1000
    - name: 工作努力得奖金500
      type: gain
      price: 500
    - name: 整修自己所有房屋，房屋每栋250，旅馆每栋1000
      type: houseDuty
      price: 250
      hotelPrice: 1000
    - name: 卖黄牛票，罚款1000
      type: cost
      price: 1000
    - name: 付保险费500
      type: cost
      price: 500
    - name: 中爱国奖券五奖得2000
      type: gain
      price: 2000
    - name: 路不拾遗失主酬劳得1000
      type: gain
      price: 1000
  happiness:
    - name: 在外滩开音乐演奏会得2000
      type: gain
      price: 1000
    - name: 修理石库门的四合院古迹花修缮费500元
      type: cost
      price: 500
    - name: 违反交通规则——闯红灯罚款2000
      type: cost
      price: 500
    - name: 拍摄龙华寺及玉佛寺美丽景观照片，参加展览得第一名得奖金1500元
      type: gain
      price: 1500
    - name: 到南京路及淮海路逛街购物，每人花费300元
      type: costTogether
      price: 300
    - name: 参观上海博物馆付门票100元
      type: cost
      price: 100
    - name: 在浦东兼差担任地陪，酬劳1000元
      type: gain
      price: 1000
    - name: 夜宿和平饭店，每人花费1800元
      type: costTogether
      price: 1800
    - name: 参观城隍庙，购买纪念玉镯水晶项链礼物，花费800元
      type: cost
      price: 800
    - name: 在东方明珠电视塔最顶层用餐，每人花费300元
      type: costTogether
      price: 300
  chances:
    - name: 直达徐家汇车站，如经过“起点”得2000
      type: through
      price: 15
    - name: 前进到天目路，如经过“起点”得2000
      type: through
      price: 24
    - name: 前进到中华路，如经过“起点”得2000
      type: through
      price: 11
    - name: 酗酒闹事，罚款200
      type: cost
      price: 200
    - name: 付户税，房屋每栋400，旅馆每栋1150
      type: houseDuty
      price: 400
      hotelPrice: 1150
    - name: 经营小本生意，获利1000
      type: gain
      price: 1000
    - name: 击落战斗机，得奖金3000
      type: gain
      price: 3000
    - name: 缴赴美留学保证金2400
      type: cost
      price: 2400
    - name: 拘票——立刻坐牢，不得经“起点”
      type: jailed
      price: 0
    - name: 出狱许可证
      type: impunity
      price: 0
    - name: 付学费1500
      type: cost
      price: 1500
    - name: 运动跳水冠军奖金1000
      type: gain
      price: 1000
    - name: 夜宿和平饭店，花费1800
      type: cost
      price: 1800
    - name: 行车超速，罚款150
      type: cost
      price: 150
    - name: 银行付你利息500
      type: gain
      price: 500
    - name: 整修自己所有房屋，房屋每栋250，旅馆每栋1000
      type: houseDuty
      price: 250
      hotelPrice: 1000

